source 'https://rubygems.org'

gem 'chef'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'berkshelf'
gem 'foodcritic'
gem 'knife-solo'
gem 'knife-spec'
gem 'rspec'
gem 'chefspec'
gem 'knife-whisk'
gem 'knife-ec2'
gem 'knife-softlayer'
