name             'cg_mysql'
maintainer       'Faizal F Zakaria'
maintainer_email 'fzakaria@codegarage.co'
license          'All rights reserved'
description      'Installs/Configures mysql with master and slave'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
supports         'ubuntu'
depends          'mysql'
depends          'apt'
