name             'base_server'
maintainer       'Faizal F Zakaria'
maintainer_email 'fzakaria@codegarage.co'
license          'All rights reserved'
description      'Installs/Configures base_server'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.4.3'
supports         'ubuntu'
depends          'apt'
depends          'chef-client'
depends          'build-essential'
