name             'application'
maintainer       'Faizal F Zakaria'
maintainer_email 'fzakaria@codegarage.co'
license          'All rights reserved'
description      'Installs/Configures application'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.5'
depends          'docker'
depends          'run-notifier'
depends          'nginx'
depends          'rvm'
